package com.mattheworth.server;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/teams") // This means URL's start with /demo (after Application path)
public class TeamController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private TeamRepository teamRepository;

	@RequestMapping(path="/create", method = RequestMethod.POST) // Map ONLY GET Requests
	public @ResponseBody String addNewTeam(@RequestParam String name
			, @RequestParam int offensiveRating, @RequestParam int defensiveRating) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Team team = new Team();
		team.setName(name);
		team.setOffensiveRating(offensiveRating);
		team.setDefensiveRating(defensiveRating);
		teamRepository.save(team);
		return "Team Created";
	}

	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody Iterable<Team> getAllTeams() {
		// This returns a JSON or XML with the users
		return teamRepository.findAll();
	}
}
